version: "3.4"
services:
  web:
    build:
      context: .
      network: host
    ports:
      - "8080:8080"
    environment:
        DB_CONNECTION_STRING: postgres://faceapp:secretPassword@storage:5432/faceapp?sslmode=disable
        APP_PORT: 8080
        ACTIVE_SHOPS: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
        LOG_LEVEL: DEBUG
        TOLERANCE: 0.45
        IS_DEV: PRODUCTION
        RECOGNIZING_METHOD: CUSTOM
        EMAIL_DOMAIN: smtp.gmail.com
        EMAIL_PORT: 587
        EMAIL_USER: kleptoman1989@gmail.com
        EMAIL_PASSWORD: Cbvajybz2
    depends_on:
      - storage
  storage:
    image: postgres
    ports:
      - "5432:5432"
    environment: 
        POSTGRES_PASSWORD: Cbvajybz13
    volumes:
        - ./pgdata:/var/lib/postgresql/data:z
        - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

