version: "3.4"
services:
  web:
    image: "valis12/faces:0.1"
    ports:
      - "8080:8080"
    environment:
        DB_CONNECTION_STRING: postgres://faceapp@storage:5432/faceapp?sslmode=disable
  storage:
    image: postgres
    environment: 
        POSTGRES_PASSWORD: Cbvajybz13
    volumes:
        - ./pgdata:/var/lib/postgres/data
        - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
